/**
 * Serialize board builder form state to YAML string.
 * Uses template strings to avoid a js-yaml dependency.
 */

export interface SerializedCriterion {
  name: string;
  weight: number;
  description: string;
}

export interface SerializedAgent {
  name: string;
  role: string;
  weight: number;
  model: string;
  veto_power: boolean;
  prompt: string;
  criteria: SerializedCriterion[];
}

export interface SerializedPanel {
  name: string;
  type: "professional" | "personal";
  version: string;
  description: string;
  agents: SerializedAgent[];
  scoring: {
    scale: number;
    passing_threshold: number;
    iteration_target: number;
  };
}

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.trim() ? pad + line : line))
    .join("\n");
}

export function escapeYaml(str: string): string {
  if (
    str.includes(":") ||
    str.includes("#") ||
    str.includes('"') ||
    str.includes("'") ||
    str.startsWith(" ") ||
    str.endsWith(" ")
  ) {
    return `"${str.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return str;
}

export function panelToYaml(panel: SerializedPanel): string {
  const lines: string[] = [
    `# BoardClaude Panel Configuration`,
    `# Generated by Board Builder`,
    ``,
    `name: ${escapeYaml(panel.name)}`,
    `type: ${panel.type}`,
    `version: "${panel.version}"`,
    `description: >`,
    `  ${panel.description}`,
    ``,
    `agents:`,
  ];

  for (const agent of panel.agents) {
    lines.push(`  - name: ${escapeYaml(agent.name)}`);
    lines.push(`    role: ${escapeYaml(agent.role)}`);
    lines.push(`    weight: ${agent.weight}`);
    lines.push(`    model: ${agent.model}`);
    if (agent.veto_power) {
      lines.push(`    veto_power: true`);
    }
    if (agent.prompt.trim()) {
      lines.push(`    prompt: |`);
      lines.push(indent(agent.prompt.trim(), 6));
    }
    lines.push(`    criteria:`);
    for (const c of agent.criteria) {
      lines.push(`      - name: ${escapeYaml(c.name)}`);
      lines.push(`        weight: ${c.weight}`);
      lines.push(`        description: ${escapeYaml(c.description)}`);
    }
    lines.push(``);
  }

  lines.push(`scoring:`);
  lines.push(`  scale: ${panel.scoring.scale}`);
  lines.push(`  passing_threshold: ${panel.scoring.passing_threshold}`);
  lines.push(`  iteration_target: ${panel.scoring.iteration_target}`);

  return lines.join("\n") + "\n";
}

export function downloadYaml(yaml: string, filename: string): void {
  const blob = new Blob([yaml], { type: "text/yaml;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".yaml") ? filename : `${filename}.yaml`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
